apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: test-db-creds
  namespace: external-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: demo-db-creds
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: db-creds
        property: username
    - secretKey: password
      remoteRef:
        key: db-creds
        property: password
