apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: backup-linkding-db
spec:
  method: plugin
  cluster:
    name: linkding-db-production-cnpg-v1
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
